### ISSUE TITLE
Bugs en tous genre

### ISSUE THREAD

**Issue by ghost** [cbaie9/palamod18#1]
- les lucky blocks en endium et les blacks ne fonctionnent pas
 - le gui du chunk analyzer est bugger (les variable pour compter le nombres de blocks)
 - - les models des spikes sont pas très beaux un si vous voulez je vous en passent un beaucoup mieux
 - l'assembling table pose un block de constructed grinder
 - les elevators ne fonctionnent pas
 - Le model et la textures du palagolem sont bugge & le gui est bugger aussi
 - la texture sur le joueur de la raimbow armor est bugge je pense qu'il manquent les .mcmeta
 - le block d'alarme allumé ne fait pas de bruit et celui eteint ne place pas celui allumer.

j'ai fait le tour des bugs que j'ai plus observer sinon très bon mod continuer comme sa les gars

**Comment by cbaie9** [comment]
1- Pour les  lucky c'est pas fini tant que tout les event ont pas été dev ( c pour ça que y'a pas de craft )
2 - Je crois connaitre le pb c a cause du forge qui change les variable depuis la 1.18 ça va être fix ( mais le block est buggé pcq le code est pas ouf )
3 - Pour les spikes c'est des modèle custom comme ça on a des colision qui marchent
4 - l'assembling table est un block sencé est supprimé ( on l'a fait en plusieurs étape pour pas corrompre les monde ) ( il servait uniquement a craft le contructed grinder soit grinder portable quand y'avais pas le grinder avec la structure comme pala
5 - Si mais les touche sont sneak pour descendre et ctrl pour monter
6 - Pas fini ( et pas le temps de dev -> Je me concentre sur la hat )
7 - Le jeu veut pas accepter les mcmeta sur les armure ( Ps : je suis triste 😭 2h de texture )
8 - Je sais mais les son sont bizzard et ça marche pas

----RESUME---
1 -> Prochain maj luckyblock
2 - Fix bientôt
3 - Si t'a le model original on veut bien
6 -> maj golem
7+8 -> Si qq'un trouve des fix je veux bien

**Comment by cbaie9** [comment]
2 - fix
7
<img width="606" alt="image" src="https://github.com/cbaie9/palamod18/assets/75169332/4f9cfc6d-19b1-4549-a3e9-f9f271127a4b">
8 -fix

**Comment by cbaie9** [comment]
b2d -> #0008
